
project_id = "kmpghammoxblhacndimq"
[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[api.headers.development]
Access-Control-Allow-Origin = "*"
Access-Control-Allow-Headers = "*"
Access-Control-Allow-Methods = "GET, POST, OPTIONS"

[db]
port = 54322

[studio]
enabled = true
port = 54323
