
project_id = "language-learning-app-with-dictation"

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.rate_limits]
points = 50
duration_seconds = 10

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
port = 54323

[functions.generate-reading-content]
verify_jwt = true
import_map = "./functions/_shared/import_map.json"

[functions.generate-reading-analysis]
verify_jwt = true

[functions.generate-vocabulary-info]  
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions]
import_map = "./functions/_shared/import_map.json"
