// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmpghammoxblhacndimq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttcGdoYW1tb3hibGhhY25kaW1xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MzcyMDUsImV4cCI6MjA2MTQxMzIwNX0.hDTz62yN8XWktfC2edLsgdinKZODP4T-VZfVJKptGao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);